---
- hosts: losangeles
  remote_user: alex
  become: true 

  tasks:
    - name: Update OS
      command: apt -y update    
         
    - name: Install required system packages for Docker CE
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip ', 'python3-setuptools', 'virtualenv']
    
    - name: Install Docker py
      command: pip3 install docker-py
    
    - name: install docker-compose
      get_url:
        url:  https://github.com/docker/compose/releases/download/1.26.0/docker-compose-{{ansible_system}}-{{ansible_userspace_architecture}}
        dest: /usr/local/bin/docker-compose
        mode: 'a+x'

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest
    
    - name: Copy file with owner and permission, using symbolic representation
      ansible.builtin.copy:
        src: docker-compose.yml
        dest: /home/alex
        owner: alex
        group: root
        mode: u=rw,g=r,o=r

    - name: Start Docker-compose
      command: 'docker-compose up -d' 
